[package]
name = "rusty-rails"
version = "0.1.0"
authors = ["Jaden Carver <jaden.carver@gmail.com>"]

[dependencies]
iron = "0.2"
router = "0.1"
params = "0.0.2"
maud = "0.7"
maud_macros = { git = "https://github.com/lfairy/maud.git" }
logger = "0.0.3"
argparse = "0.2"
staticfile = "0.1"
glob = "0.2.10"
diesel = "0.5.0"
diesel_codegen = { version = "0.5.0", default-features = false, features = ["nightly", "postgres"] }
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
serde = "*"
serde_json = "*"

[[bin]]
name = "start"
path = "app/server.rs"

[[bin]]
name = "task"
path = "src/tasks.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"
